set quiet

set cpu 11/70
set tc enabled
attach rk0 disk.rk

# DC11 serial interface
set dci enabled
set dci lines=16
set dco0 dataset
# 707/1200: 1200-7E1 (1200 baud, 7 bits, even parity, 1 stop bit)
# 703, 43: 300-7E1 (300 baud, 7 bits, even parity, 1 stop bit)
# VT220 with default config: 9600-8N1 (9600 baud, 8 bits, no parity, 1 stop bit)
attach dci line=0,connect=/dev/ttyUSB0;1200-7E1
attach dci line=1,connect=/dev/ttyUSB1;9600-8N1
#attach dci line=0,4000
#attach dci line=1,4001
attach dci line=2,4002
attach dci line=3,4003
attach dci line=4,4004
attach dci line=5,4005
attach dci line=6,4006
attach dci line=7,4007
attach dci line=8,4008
attach dci line=9,4009
attach dci line=10,4010
attach dci line=11,4011
attach dci line=12,4012
attach dci line=13,4013
attach dci line=14,4014
attach dci line=15,4015

set realcons host=localhost
set realcons panel=11/70
set realcons interval=1
set realcons connect

deposit sr 2

echo
send "k"
expect "\r" send "unix\r"; go

boot rk
