set quiet

set cpu 11/70
set tc enabled
attach rk0 disk.rk

!mkdir -p logs

# Main KL11 console
set log logs/kl0.log

# DC11 terminal multiplexer
set dci enabled
set dci lines=16
set dco0 dataset
# 707/1200: 1200-7E1 (1200 baud, 7 bits, even parity, 1 stop bit)
# 703, 43: 300-7E1 (300 baud, 7 bits, even parity, 1 stop bit)
# VT220 with default config: 9600-8N1 (9600 baud, 8 bits, no parity, 1 stop bit)
attach dci line=0,connect=/dev/ttyUSB0;1200-7E1
#attach dci line=1,connect=/dev/ttyUSB1;9600-8N1
#attach dci line=0,4000
attach dci line=1,4001
attach dci line=2,4002
attach dci line=3,4003
attach dci line=4,4004
attach dci line=5,4005
attach dci line=6,4006
attach dci line=7,4007
attach dci line=8,4008
attach dci line=9,4009
attach dci line=10,4010
attach dci line=11,4011
attach dci line=12,4012
attach dci line=13,4013
attach dci line=14,4014
attach dci line=15,4015
set dco0 log=logs/dc0.log
set dco1 log=logs/dc1.log
set dco2 log=logs/dc2.log
set dco3 log=logs/dc3.log
set dco4 log=logs/dc4.log
set dco5 log=logs/dc5.log
set dco6 log=logs/dc6.log
set dco7 log=logs/dc7.log
set dco8 log=logs/dc8.log
set dco9 log=logs/dc9.log
set dco10 log=logs/dc10.log
set dco11 log=logs/dc11.log
set dco12 log=logs/dc12.log
set dco13 log=logs/dc13.log
set dco14 log=logs/dc14.log
set dco15 log=logs/dc15.log

# Extra KL11 terminal lines
set dli enabled
set dli lines=15
attach dli line=0,4016
attach dli line=1,4017
attach dli line=2,4018
attach dli line=3,4019
attach dli line=4,4020
attach dli line=5,4021
attach dli line=6,4022
attach dli line=7,4023
attach dli line=8,4024
attach dli line=9,4025
attach dli line=10,4026
attach dli line=11,4027
attach dli line=12,4028
attach dli line=13,4029
attach dli line=14,4030
# DLO defaults to UC (uppercase)
set dlo0 7b,log=logs/kl1.log
set dlo1 7b,log=logs/kl2.log
set dlo2 7b,log=logs/kl3.log
set dlo3 7b,log=logs/kl4.log
set dlo4 7b,log=logs/kl5.log
set dlo5 7b,log=logs/kl6.log
set dlo6 7b,log=logs/kl7.log
set dlo7 7b,log=logs/kl8.log
set dlo8 7b,log=logs/kl9.log
set dlo9 7b,log=logs/kl10.log
set dlo10 7b,log=logs/kl11.log
set dlo11 7b,log=logs/kl12.log
set dlo12 7b,log=logs/kl13.log
set dlo13 7b,log=logs/kl14.log
set dlo14 7b,log=logs/kl15.log

set realcons host=localhost
set realcons panel=11/70
set realcons interval=1
set realcons connect

deposit sr 2

echo
send "k"
expect "\r" send "unix\r"; go

boot rk
